version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: DockerFile
    ports:
      - "3001:3001"
  client:
    build:
      context: ./
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    depends_on:
      - server
